CREATE DATABASE QUANLYCAPHE

USE QUANLYCAPHE

CREATE TABLE NHANVIEN (
	MANV int NOT NULL IDENTITY(1,1),
    TENNV NVARCHAR(50) UNIQUE,
	DIACHI NVARCHAR(200) DEFAULT N'Chưa xác định',
	SDT NVARCHAR(12),
	NGAYSINH DATETIME DEFAULT GETDATE(), 
	TENTK NVARCHAR(50),
	PASSWD NVARCHAR(50),
	CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANV)
)
ALTER TABLE NHANVIEN
ADD CONSTRAINT CHECK_TUOI CHECK (YEAR(GETDATE()) - (YEAR(NGAYSINH)) > 18)

CREATE TABLE KHACHHANG (
	MAKH NCHAR(10) NOT NULL,
	TENKH NVARCHAR(50),
	DIACHI NVARCHAR(200),
	EMAIL NVARCHAR(150),
	NGAYSINH DATETIME,
	SDT NVARCHAR(20) UNIQUE,
	CONSTRAINT PK_KHACHHANG PRIMARY KEY (MAKH)
)

CREATE TABLE SANPHAM (
	MASP NCHAR(10) NOT NULL,
	TENSP NVARCHAR(200) UNIQUE,
	CHITIET NVARCHAR(500),
	GIA FLOAT,
	CONSTRAINT PK_SANPHAM PRIMARY KEY (MASP)

)

CREATE TABLE HOADON (
	MAHD int NOT NULL IDENTITY(1,1),
	MANV int NOT NULL,
	MAKH NCHAR(10) NOT NULL,
	TONGTIEN FLOAT,  
	NGAYMUA DATETIME,
	CHUTHICH NVARCHAR(500)
	CONSTRAINT PK_HOADON PRIMARY KEY (MAHD),
	CONSTRAINT FK_HOADON_NHANVIEN FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV),
	CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)
)

CREATE TABLE CTHOADON (
	MAHD int NOT NULL,
	MASP NCHAR(10) NOT NULL,
	SOLUONG INT check (SOLUONG > 0),
	GIA FLOAT,
	CONSTRAINT FK_CTHOADON_SANPHAM FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP),
	CONSTRAINT FK_CTHOADON_HOADON FOREIGN KEY(MAHD) REFERENCES HOADON(MAHD),
)

ALTER TABLE CTHOADON
ADD CONSTRAINT CHECK_SOLUONG CHECK (SOLUONG > 0 AND SOLUONG != NULL)

SET DATEFORMAT DMY;
INSERT INTO NHANVIEN VALUES
(N'ĐOÀN TRUNG TÍNH',N'PHÚ YÊN','0338952114','02/01/1999','tinh','123'),
(N'PHÚC HỒ',N'HỒ CHÍ MINH','0799493114','25/10/1998','phuc','phuc'),
(N'LÊ VĂN SỸ',N'HỒ CHÍ MINH','0799493112','2/8/1997','admin','1')

INSERT INTO KHACHHANG VALUES
('KH001',N'ĐÀO HỮU MINH',N'LONG AN','HUUMINH01@GMAIL.COM','20/2/1999','01213552565'),
('KH002',N'LÊ THỊ MỘNG',N'TÂY NINH','HUUMINH01@GMAIL.COM','10/1/2002','01668952111'),
('KH003',N'DOÃN VĂN LỘC',N'ĐỒNG NAI','HUUMINH01@GMAIL.COM','2/9/1979','01628222640')


INSERT INTO SANPHAM VALUES
('SP001',N'CÀ PHÊ',N'CÀ PHÊ HẠT',30000),
('SP002',N'TRÀ SỮA',N'TRÀ SỮA THÁI ĐỎ',20000),
('SP003',N'NƯỚC TĂNG LỰC',N'THÁI LAND',20000),
('SP004',N'CÀ PHÊ ĐEN',N'CÀ PHÊ PHA SẴN',20000),
('SP005',N'NƯỚC SUỐI',N'LAVIE',10000)

INSERT INTO HOADON VALUES
('1','KH003',NULL,'20/7/2021',N'KHÔNG ĐỔI'),
('2','KH002',NULL,'20/8/2021',N'KHÔNG ĐỔI'),
('3','KH001',NULL,'20/1/2021',N' ĐỔI TRẢ')

ALTER TABLE CTHOADON
ADD THANHTIEN float default null

INSERT INTO CTHOADON VALUES
('1','SP002',10,20000,200000),
('1','SP001',5,30000,150000),
('2','SP003',20,20000,400000),
('2','SP004',10,20000,200000)


CREATE TRIGGER AUTOUPDATETONGTIENHD
ON CTHOADON
FOR DELETE, INSERT, UPDATE
AS
	UPDATE HOADON
	set TONGTIEN =  (SELECT SUM(THANHTIEN) FROM CTHOADON WHERE CTHOADON.MAHD = INSERTED.MAHD )
	from HOADON,INSERTED
	where HOADON.MAHD = INSERTED.MAHD

GO

CREATE trigger TONGTIENCTHD on CTHOADON
    for insert, update, delete
    as
  
    	update CTHOADON
    	set 
    		THANHTIEN = inserted.SoLuong * inserted.GIA
    	from 
    		inserted,
    		CTHOADON
    	where 
		 CTHOADON.MASP = inserted.MASP
go


CREATE FUNCTION LoginV1 
(
	@Username VARCHAR(50),
	@Password VARCHAR(MAX)
)
RETURNS int 
AS
BEGIN
	DECLARE @resutl int
	IF EXISTS(SELECT * FROM NHANVIEN WHERE TENTK = @Username AND PASSWD = @Password)
		return 1

	RETURN 0
END

CREATE FUNCTION LoginV2
(
	@Username VARCHAR(50),
	@Password VARCHAR(MAX)
)
RETURNS @rtnTable table (MANV int,
    TENNV NVARCHAR(50) ,
	DIACHI NVARCHAR(200) ,
	SDT NVARCHAR(12),
	NGAYSINH DATETIME , 
	TENTK NVARCHAR(50),
	PASSWD NVARCHAR(50))
AS
BEGIN
	
	INSERT INTO  @rtnTable SELECT * FROM NHANVIEN WHERE TENTK = @Username AND PASSWD = @Password
	return 
END

select * FROM   LoginV2('admin','1')


DECLARE CURSOR_TONGTIENHD CURSOR
DYNAMIC 
FOR SELECT HOADON.MAHD FROM HOADON,CTHOADON WHERE CTHOADON.MAHD = HOADON.MAHD
OPEN CURSOR_TONGTIENHD
DECLARE @MAHD NCHAR(10)
FETCH NEXT FROM CURSOR_TONGTIENHD INTO @MAHD
WHILE (@@FETCH_STATUS = 0)
BEGIN 
	
	UPDATE HOADON
	SET TONGTIEN = (SELECT sum(THANHTIEN) FROM CTHOADON,HOADON WHERE CTHOADON.MAHD = HOADON.MAHD AND HOADON.MAHD = @MAHD)
	WHERE HOADON.MAHD = @MAHD
	FETCH NEXT FROM CURSOR_TONGTIENHD INTO @MAHD
END

CLOSE CURSOR_TONGTIENHD            
DEALLOCATE CURSOR_TONGTIENHD

DECLARE CURSOR_GIA CURSOR
DYNAMIC 
FOR SELECT CTHOADON.MASP FROM SANPHAM,CTHOADON WHERE SANPHAM.MASP = CTHOADON.MASP
OPEN CURSOR_GIA
DECLARE @MASP NCHAR(10)
FETCH NEXT FROM CURSOR_GIA INTO @MASP
WHILE (@@FETCH_STATUS = 0)
BEGIN 
	
	UPDATE CTHOADON
	SET GIA = (SELECT sum(SOLUONG * SANPHAM.GIA) FROM SANPHAM,CTHOADON WHERE SANPHAM.MASP = CTHOADON.MASP AND CTHOADON.MASP = @MASP)
	WHERE CTHOADON.MASP = @MASP
	FETCH NEXT FROM CURSOR_GIA INTO @MASP
END

CLOSE CURSOR_GIA              
DEALLOCATE CURSOR_GIA


CREATE PROCEDURE InsertNHANVIEN 
	@TENNV NVARCHAR(30),
        @DIACHI NVARCHAR(100),
        @SDT NCHAR(12),
		@NGAYSINH DATE,
	@TENTK NVARCHAR(30),
	@PASSWD NVARCHAR(30)
AS 
   INSERT INTO NHANVIEN(TENNV,DIACHI,SDT,NGAYSINH,TENTK,PASSWD)
   VALUES(@TENNV,@DIACHI,@SDT,@NGAYSINH,@TENTK,@PASSWD) 


CREATE PROC UpdateNHANVIEN(@MANV int,@TENNV NVARCHAR(80),@DIACHI NVARCHAR(150),@SDT NCHAR(12), @NGAYSINH DATE, @TENTK NVARCHAR(50),@PASSWD NVARCHAR(30))
AS BEGIN
    IF @MANV=0 BEGIN
        INSERT INTO NHANVIEN 
        VALUES(@TENNV, @DIACHI, @SDT, @NGAYSINH, @TENTK, @PASSWD);
    END;
    ELSE BEGIN
        UPDATE dbo.NHANVIEN
        SET  TENNV=@TENNV, DIACHI=@DIACHI,SDT = @SDT,NGAYSINH = @NGAYSINH, TENTK = @TENTK, PASSWD = @PASSWD
        WHERE MANV=@MANV
    END;
END;

CREATE PROC DeleteNHANVIEN
@MANV AS int
AS
BEGIN
	DELETE FROM NHANVIEN WHERE MANV = @MANV
END

CREATE PROC SearchNHANVIEN 
@TENNV AS NVARCHAR(150)
AS
BEGIN
	SELECT MANV,TENNV, DIACHI, SDT, NGAYSINH, TENTK, PASSWD FROM NHANVIEN
	WHERE @TENNV = '' OR TENNV LIKE '%' + @TENNV + '%'    
END


CREATE PROC THEMSP
(
	@TENSP NVARCHAR(100),
	@GIA FLOAT,
	@MASP NCHAR(10),
	@CHITIET NCHAR(100)
)
AS
	INSERT INTO SANPHAM(MASP,TENSP,CHITIET,GIA) VALUES(@MASP,@TENSP,@CHITIET,@GIA)
GO

CREATE PROC UPDATESP
(
	@TENSP NVARCHAR(100),
	@GIA FLOAT,
	@MASP NCHAR(10),
	@CHITIET NCHAR(100)
)
AS
	UPDATE SANPHAM SET TENSP = @TENSP, CHITIET = @CHITIET, GIA = @GIA WHERE MASP = @MASP
GO

CREATE PROC DELSANPHAM
(
	@MASP NCHAR(10)
)
AS
	DELETE FROM SANPHAM WHERE MASP = @MASP
GO

SELECT * FROM dbo.NHANVIEN
WHERE TENNV LIKE N'%T%'


